package vistas;

import control.*;
import modelo.*;

import java.util.logging.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.*;

/**
 * @author Gomez Jon Darian, Guardia Lucero Santiago Agustín, Heredia Leandro
 */
public class VistaMenu extends javax.swing.JInternalFrame {

    private MenuData md;
    private ArrayList<Menu> listaMenues;
    
    private Conexion con;
    
    private DefaultTableModel modelo;
    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        try {
            initComponents();
            
            con = new Conexion("jdbc:mysql://localhost/paquetes_turisticos", "root", "");
            md = new MenuData(con);
            listaMenues = (ArrayList)md.obtenerMenues();
            
            modelo = new DefaultTableModel();
            armarCabecera();
            
            btnGrupo.add(jrTodos);
            btnGrupo.add(jrActivos);
            btnGrupo.add(jrInactivos);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        btnGrupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabMenues = new javax.swing.JTable();
        jtMenu = new javax.swing.JTextField();
        jtCosto = new javax.swing.JTextField();
        jcActivo = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jrTodos = new javax.swing.JRadioButton();
        jrActivos = new javax.swing.JRadioButton();
        jrInactivos = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Menu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tipo menu:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Costo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Activo");

        btnCargar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.setEnabled(false);
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jtabMenues.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtabMenues);

        jtMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtMenu.setEnabled(false);

        jtCosto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtCosto.setEnabled(false);

        jcActivo.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Lista de Menues");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jrTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrTodos.setText("Todos");

        jrActivos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrActivos.setText("Activos");

        jrInactivos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrInactivos.setText("Inactivos");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCargar)
                                .addGap(58, 58, 58)
                                .addComponent(btnNuevo)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(104, 104, 104))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcActivo)
                            .addComponent(jtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(jrTodos)
                            .addGap(18, 18, 18)
                            .addComponent(jrActivos)
                            .addGap(30, 30, 30)
                            .addComponent(jrInactivos)
                            .addGap(115, 115, 115))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnBuscar)
                            .addGap(198, 198, 198)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(127, 127, 127))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrTodos)
                            .addComponent(jrActivos)
                            .addComponent(jrInactivos))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcActivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnCargar))
                        .addGap(23, 23, 23))))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        try {
            String tipo = jtMenu.getText();
            double costo = Double.parseDouble(jtCosto.getText());
            boolean activo = jcActivo.isSelected();
            
            if(soloTexto(tipo)) {
                Menu m = new Menu(tipo, costo, activo);
                md.agregarMenu(m);
                
            } else {
                JOptionPane.showMessageDialog(this, "Error en el tipo de Menu");
            }
            
            borrarFila();
        } catch (Throwable ex ) {
            JOptionPane.showMessageDialog(this, "Error en ingresar los datos");
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        jtMenu.setText("");
        jtCosto.setText("");
        jcActivo.setSelected(false);
        
        activarCampos();
        borrarFila();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        borrarFila();
        
        boolean check1 = jrTodos.isSelected();
        boolean check2 = jrActivos.isSelected();
        boolean check3 = jrInactivos.isSelected();
        
        if(check1) {
            llenarTablaTodos();
        } else if (check2) {
            llenarTablaActivos();
        } else if (check3) {
            llenarTablaInactivos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void activarCampos() {
        jtMenu.setEnabled(true);
        jtCosto.setEnabled(true);
        jcActivo.setEnabled(true);
        btnCargar.setEnabled(true);
    }
    
    private boolean soloTexto(String str) {
        char[] caracteres = str.toCharArray();
        for (int i = 0; i < caracteres.length; i++) {
            if (Character.isDigit(caracteres[i])) {
                return false;
            }
        }
        return true;
    }
    
    private void armarCabecera() {
        ArrayList<Object> titulos = new ArrayList<>();
        
        titulos.add("ID");
        titulos.add("Tipo Menu");
        titulos.add("Costo");
        titulos.add("Activo");
        
        for (Object titulo: titulos) {
            modelo.addColumn(titulo);
        }
        
        jtabMenues.setModel(modelo);
    }
    
    private void borrarFila() {
        int filas = modelo.getRowCount() - 1;
        
        for (int cont = filas; cont >= 0; cont--) {
            modelo.removeRow(cont);
        }
    }
    
    private void llenarTablaTodos() {
        for (Menu m: listaMenues) {
            modelo.addRow(new Object[]{m.getIdMenu(), m.getTipoMenu(), m.getCosto(), m.isActivo()});
        }
    }
    
    private void llenarTablaActivos() {
        for (Menu m: listaMenues) {
            if (m.isActivo()) {
                modelo.addRow(new Object[]{m.getIdMenu(), m.getTipoMenu(), m.getCosto(), m.isActivo()});
            }
        }
    }
    
    private void llenarTablaInactivos() {
        for (Menu m: listaMenues) {
            if (!m.isActivo()) {
                modelo.addRow(new Object[]{m.getIdMenu(), m.getTipoMenu(), m.getCosto(), m.isActivo()});
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargar;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JCheckBox jcActivo;
    private javax.swing.JRadioButton jrActivos;
    private javax.swing.JRadioButton jrInactivos;
    private javax.swing.JRadioButton jrTodos;
    private javax.swing.JTextField jtCosto;
    private javax.swing.JTextField jtMenu;
    private javax.swing.JTable jtabMenues;
    // End of variables declaration//GEN-END:variables
}
